name: Deploy to Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: "87.107.155.116"
        username: "root"
        password: "DOjsy8rcx7"
        port: 9011
        script: |
          cd /production/www/gymclub-backend && git pull origin main && cd /production && docker compose exec php bash -c "cd gymclub-backend && composer install"
          
